import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, RefreshCw, Store, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { api } from "@/lib/api";
import { customGranularity, dateRangeForPreset, type DatePreset } from "@/insightsLogic";
import { axisTicks, categoryColor, comparisonText, dateLabel, groupSmallCategories, meaningfulChange, money, signedMoney, xTickIndexes } from "@/insightsVisualization";

type Summary = { total_cents: number; personal_cents: number; shared_cents: number; transaction_count: number; average_cents: number };
type Breakdown = { name: string; amount_cents: number; transaction_count?: number; percentage?: number; previous_amount_cents?: number };
type Trend = { period: string; total_cents: number; personal_cents: number; shared_cents: number; transactions: number };
type Insights = {
  range: { start_date: string; end_date: string; previous_start_date: string; previous_end_date: string; granularity: "day" | "week" | "month" };
  summary: Summary; comparison: Summary; trend: Trend[]; category_breakdown: Breakdown[];
  subcategory_breakdown: Breakdown[]; merchant_breakdown: Breakdown[];
  personal_shared: { personal: number; shared: number }; shared_people: Breakdown[]; shared_groups: Breakdown[];
  category_trend: { period: string; categories: Record<string, number> }[]; notable_changes: { kind: string; direction: string; label: string; amount_cents: number; detail: string }[];
  accounts: string[]; categories: string[]; merchants: string[];
  data_quality: { unknown_share_transactions: number; pending_review_cents: number; uncategorized_cents: number; pending_transactions_excluded: boolean };
};

const presets: [DatePreset, string][] = [["7d", "7D"], ["30d", "30D"], ["this_month", "This Month"], ["last_month", "Last Month"], ["90d", "90D"], ["this_quarter", "This Quarter"], ["last_quarter", "Last Quarter"], ["ytd", "YTD"], ["custom", "Custom"]];

export function InsightsDashboard() {
  const [preset, setPreset] = useState<DatePreset>("30d");
  const initial = dateRangeForPreset("30d");
  const [start, setStart] = useState(initial.start); const [end, setEnd] = useState(initial.end);
  const [account, setAccount] = useState(""); const [category, setCategory] = useState("");
  const [merchant, setMerchant] = useState(""); const [merchantInput, setMerchantInput] = useState("");
  const [reviewType, setReviewType] = useState("all"); const [basis, setBasis] = useState("card");
  const [data, setData] = useState<Insights | null>(null); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const [topCount, setTopCount] = useState(5);
  const [sharedMode, setSharedMode] = useState<"people" | "groups">("people");
  const [trendMode, setTrendMode] = useState<"total" | "split">("total");

  useEffect(() => { const timer = window.setTimeout(() => setMerchant(merchantInput.trim()), 300); return () => window.clearTimeout(timer); }, [merchantInput]);
  useEffect(() => {
    if (!start || !end || start > end) return;
    const controller = new AbortController(); setLoading(true); setError("");
    const params = new URLSearchParams({ start_date: start, end_date: end, review_type: reviewType, spend_basis: basis, granularity: customGranularity(start, end) });
    if (account) params.set("account_id", account); if (category) params.set("category", category); if (merchant) params.set("merchant", merchant);
    api<Insights>(`/api/insights/spending?${params}`, { signal: controller.signal }).then(setData).catch((value) => { if (!controller.signal.aborted) setError(typeof value?.detail === "string" ? value.detail : "We couldn't load spending insights."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [start, end, account, category, merchant, reviewType, basis]);

  function choosePreset(value: DatePreset) { setPreset(value); if (value !== "custom") { const range = dateRangeForPreset(value); setStart(range.start); setEnd(range.end); } }
  function clearFilters() { choosePreset("30d"); setAccount(""); setCategory(""); setMerchant(""); setMerchantInput(""); setReviewType("all"); setBasis("card"); }
  const filtered = preset !== "30d" || account || category || merchant || reviewType !== "all" || basis !== "card";

  if (error) return <CompactMessage title="Insights unavailable" detail={error} action={() => { setMerchant((value) => `${value} `); }} />;
  return <section className="space-y-5" aria-label="Spending insights">
    <Card className="z-10 bg-white/95 backdrop-blur lg:sticky lg:top-2 lg:shadow-md"><CardContent className="space-y-4 p-4">
      <div className="flex gap-2 overflow-x-auto pb-1" aria-label="Date range presets">{presets.map(([value,label]) => <button key={value} type="button" aria-pressed={preset===value} onClick={() => choosePreset(value)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-semibold focus-visible:ring-2 focus-visible:ring-indigo-500 ${preset===value?"border-indigo-600 bg-indigo-600 text-white":"border-slate-200 bg-white text-slate-700 hover:border-indigo-300"}`}>{label}</button>)}</div>
      {preset === "custom" ? <div className="flex flex-wrap items-end gap-3"><DateField label="Start date" value={start} onChange={setStart}/><span className="pb-2 text-slate-400">→</span><DateField label="End date" value={end} onChange={setEnd}/>{start>end?<p role="alert" className="text-sm text-rose-700">Start date must not be after end date.</p>:null}</div>:null}
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Select label="Account" value={account} onChange={setAccount} options={data?.accounts||[]} all="All Accounts"/><Select label="Category" value={category} onChange={setCategory} options={data?.categories||[]} all="All Categories"/><label className="grid gap-1 text-xs font-semibold text-slate-700">Merchant<Input value={merchantInput} onChange={e=>setMerchantInput(e.target.value)} placeholder="All Merchants"/></label><Select label="Type" value={reviewType} onChange={setReviewType} options={["personal","shared"]} all="All"/><label className="grid gap-1 text-xs font-semibold text-slate-700">Spending basis<select className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm" value={basis} onChange={e=>setBasis(e.target.value)}><option value="card">Card Spend</option><option value="actual_share">My Actual Share</option></select></label></div>
      {filtered?<div className="flex flex-wrap items-center gap-2">{preset!=="30d"?<Chip label={`Range: ${presets.find(([value])=>value===preset)?.[1]}`} onRemove={()=>choosePreset("30d")}/>:null}{account?<Chip label={`Account: ${account}`} onRemove={()=>setAccount("")}/>:null}{category?<Chip label={`Category: ${category}`} onRemove={()=>setCategory("")}/>:null}{merchant?<Chip label={`Merchant: ${merchant}`} onRemove={()=>{setMerchant("");setMerchantInput("");}}/>:null}{reviewType!=="all"?<Chip label={`Type: ${title(reviewType)}`} onRemove={()=>setReviewType("all")}/>:null}{basis!=="card"?<Chip label="Basis: My Actual Share" onRemove={()=>setBasis("card")}/>:null}<Button variant="ghost" size="sm" onClick={clearFilters}><X className="h-4 w-4"/>Clear all</Button></div>:null}
    </CardContent></Card>
    {loading && !data ? <DashboardSkeleton/> : data && data.summary.transaction_count ? <>
      {basis==="actual_share"&&data.data_quality.unknown_share_transactions?<p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{data.data_quality.unknown_share_transactions} shared transaction{data.data_quality.unknown_share_transactions===1?" has":"s have"} no confirmed share and {data.data_quality.unknown_share_transactions===1?"is":"are"} excluded from this view.</p>:null}
      {data.data_quality.pending_review_cents>=10_000?<p className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">{money(data.data_quality.pending_review_cents)} is still awaiting review and may affect category totals.</p>:null}
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Total Spend" value={data.summary.total_cents} previous={data.comparison.total_cents}/><Kpi label="Personal Spend" value={data.summary.personal_cents} previous={data.comparison.personal_cents}/><Kpi label="Shared Spend" value={data.summary.shared_cents} previous={data.comparison.shared_cents}/><Kpi label="Transactions" raw={String(data.summary.transaction_count)} previousRaw={data.comparison.transaction_count}/><Kpi label="Average Transaction" value={data.summary.average_cents} previous={data.comparison.average_cents}/></div>
      <div className="grid gap-5 xl:grid-cols-[2fr_1fr]"><ChartCard title="Spend Over Time" action={<Toggle values={["total","split"]} labels={["Total","Personal vs Shared"]} value={trendMode} onChange={v=>setTrendMode(v as typeof trendMode)}/>}><LineChart values={data.trend} split={trendMode==="split"} granularity={data.range.granularity}/></ChartCard><ChartCard title="Spending by Category"><Donut items={data.category_breakdown} total={data.summary.total_cents} onSelect={setCategory}/></ChartCard></div>
      {category?<ChartCard title={`${category} detail`}><Bars items={data.subcategory_breakdown} onSelect={()=>undefined}/></ChartCard>:null}
      <div className="grid gap-5 lg:grid-cols-2"><ChartCard title="Category spending"><Bars items={data.category_breakdown} comparison categoryColors total={data.summary.total_cents} onSelect={setCategory}/></ChartCard><ChartCard title="Top Merchants" action={<Toggle values={["5","10"]} labels={["Top 5","Top 10"]} value={String(topCount)} onChange={v=>setTopCount(Number(v))}/>}><Bars items={data.merchant_breakdown.slice(0,topCount)} showCounts onSelect={(value)=>{setMerchant(value);setMerchantInput(value);}}/></ChartCard></div>
      <ChartCard title="Personal versus Shared"><StackedSplit values={data.personal_shared} onSelect={setReviewType}/></ChartCard>
      {(sharedMode==="people"?data.shared_people:data.shared_groups).length?<ChartCard title="Shared With" action={<Toggle values={["people","groups"]} labels={["People","Groups"]} value={sharedMode} onChange={v=>setSharedMode(v as typeof sharedMode)}/>}><Bars items={(sharedMode==="people"?data.shared_people:data.shared_groups).slice(0,10)} onSelect={()=>undefined}/></ChartCard>:<p className="text-sm text-slate-600">No shared spending in this period.</p>}
      <ChartCard title="Category Trend"><CategoryTrend values={data.category_trend} granularity={data.range.granularity}/></ChartCard>
      <ChartCard title="What Changed"><Changes items={data.notable_changes}/></ChartCard>
    </> : data ? <CompactMessage title="No spending data for this period" detail="Try a wider date range or sync transactions."/> : null}
  </section>;
}

function Kpi({label,value,previous,raw,previousRaw}:{label:string;value?:number;previous?:number;raw?:string;previousRaw?:number}){const current=value??Number(raw||0);const prior=previous??previousRaw;const comparison=prior===undefined?null:raw?countComparison(current,prior):comparisonText(current,prior);return <Card><CardContent className="min-h-28 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-600">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{raw||money(value||0)}</p><div className="mt-1 text-xs text-slate-600">{comparison?<><p>{comparison.primary}</p>{comparison.secondary?<p>{comparison.secondary}</p>:null}</>:<p>No comparison available</p>}</div></CardContent></Card>}
function ChartCard({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <Card><CardHeader className="flex-row items-center justify-between gap-3"><CardTitle className="text-base">{title}</CardTitle>{action}</CardHeader><CardContent>{children}</CardContent></Card>}
function Bars({items,onSelect,comparison=false,categoryColors=false,showCounts=false,total=0}:{items:Breakdown[];onSelect:(name:string)=>void;comparison?:boolean;categoryColors?:boolean;showCounts?:boolean;total?:number}){const max=Math.max(1,...items.map(v=>Math.abs(v.amount_cents)));return <div className="space-y-3" role="list">{items.map((item)=><button type="button" key={item.name} onClick={()=>onSelect(item.name)} className="block w-full rounded-lg p-1 text-left hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-indigo-500" aria-label={`${item.name}, ${money(item.amount_cents)}`}><span className="flex justify-between gap-3 text-sm"><span className="truncate font-medium text-slate-800">{item.name}</span><span>{money(item.amount_cents)}</span></span>{showCounts&&item.transaction_count?<span className="mt-0.5 block text-xs text-slate-500">{item.transaction_count} transaction{item.transaction_count===1?"":"s"}</span>:null}<span className="mt-1 block h-2 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-indigo-600" style={{width:`${Math.max(2,Math.abs(item.amount_cents)/max*100)}%`,backgroundColor:categoryColors?categoryColor(item.name):undefined}}/></span>{comparison&&meaningfulChange(item.amount_cents,item.previous_amount_cents||0,total)?<span className="mt-1 block text-xs text-slate-500">{signedMoney(item.amount_cents-(item.previous_amount_cents||0))} vs previous period</span>:null}</button>)}</div>}
function Donut({items,total,onSelect}:{items:Breakdown[];total:number;onSelect:(name:string)=>void}){const grouped=groupSmallCategories(items);const groupedTotal=grouped.reduce((sum,item)=>sum+item.amount_cents,0);let offset=0;return <div className="grid gap-4 sm:grid-cols-[150px_1fr] xl:grid-cols-1 2xl:grid-cols-[150px_1fr]"><div className="relative mx-auto h-36 w-36 rounded-full" style={{background:`conic-gradient(${grouped.map((item)=>{const start=offset;offset+=groupedTotal?item.amount_cents/groupedTotal*100:0;return `${categoryColor(item.name)} ${start}% ${offset}%`}).join(",")})`}} aria-label={`Category composition, ${money(total)} total`}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-white text-center"><strong>{money(total)}</strong><span className="text-xs text-slate-500">Total spending</span></div></div><div className="space-y-1">{grouped.map((item)=>{const percentage=groupedTotal?Math.round(item.amount_cents/groupedTotal*100):0;return <button key={item.name} type="button" onClick={()=>onSelect(item.name)} title={`${item.name}\n${money(item.amount_cents)} · ${percentage}%`} className="flex w-full items-center justify-between gap-2 rounded p-1.5 text-xs hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-indigo-500"><span className="flex min-w-0 items-center gap-2"><span className="h-2.5 w-2.5 shrink-0 rounded-sm" style={{backgroundColor:categoryColor(item.name)}}/><span className="truncate">{item.name}</span></span><span>{money(item.amount_cents)} · {percentage}%</span></button>})}</div></div>}
function LineChart({values,split,granularity}:{values:Trend[];split:boolean;granularity:"day"|"week"|"month"}){const ticks=axisTicks(Math.max(1,...values.map(v=>v.total_cents)));const ceiling=ticks.at(-1)||1;const left=58,right=620,top=18,bottom=238;const x=(index:number)=>values.length===1?(left+right)/2:left+index/(values.length-1)*(right-left);const y=(amount:number)=>bottom-amount/ceiling*(bottom-top);const points=(key:keyof Trend)=>values.map((v,i)=>`${x(i)},${y(Number(v[key]))}`).join(" ");const dateTicks=xTickIndexes(values.length);return <div className="min-h-[260px] w-full overflow-hidden"><svg viewBox="0 0 640 280" className="h-[260px] w-full sm:h-[300px]" role="img" aria-label="Spend over time chart">{ticks.map(tick=><g key={tick}><line x1={left} x2={right} y1={y(tick)} y2={y(tick)} stroke="#e2e8f0"/><text x={left-8} y={y(tick)+4} textAnchor="end" fontSize="11" fill="#64748b">{money(tick)}</text></g>)}{split?<><polyline points={points("personal_cents")} fill="none" stroke="#475569" strokeWidth="3"/><polyline points={points("shared_cents")} fill="none" stroke="#4f46e5" strokeWidth="3"/></>:<polyline points={points("total_cents")} fill="none" stroke="#4f46e5" strokeWidth="3"/>}{values.map((value,index)=>{const tooltip=split?`${dateLabel(value.period,granularity,true)}\nPersonal: ${money(value.personal_cents)}\nShared: ${money(value.shared_cents)}\nTotal: ${money(value.total_cents)}\nTransactions: ${value.transactions}`:`${dateLabel(value.period,granularity,true)}\nTotal spend: ${money(value.total_cents)}\nTransactions: ${value.transactions}`;return <g key={value.period} tabIndex={0} aria-label={tooltip}><title>{tooltip}</title><circle cx={x(index)} cy={y(split?value.total_cents:value.total_cents)} r="8" fill="transparent"/><circle cx={x(index)} cy={y(value.total_cents)} r="3" fill="#4f46e5"/></g>})}{dateTicks.map(index=><text key={values[index].period} x={x(index)} y="264" textAnchor="middle" fontSize="10" fill="#64748b">{dateLabel(values[index].period,granularity)}</text>)}</svg><div className="sr-only">{values.map(v=>`${dateLabel(v.period,granularity,true)}: total ${money(v.total_cents)}, personal ${money(v.personal_cents)}, shared ${money(v.shared_cents)}, ${v.transactions} transactions`).join("; ")}</div></div>}
function StackedSplit({values,onSelect}:{values:{personal:number;shared:number};onSelect:(v:string)=>void}){const total=values.personal+values.shared;const personal=total?Math.round(values.personal/total*100):0;const shared=100-personal;return <div className="space-y-3"><div className="flex h-10 overflow-hidden rounded-lg" aria-label={`Personal ${personal}%, Shared ${shared}%`}><button type="button" onClick={()=>onSelect("personal")} aria-label={`Filter Personal, ${money(values.personal)}, ${personal}%`} className="bg-slate-500 text-xs font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500" style={{width:`${personal}%`}}>{personal>=15?`Personal ${personal}%`:null}</button><button type="button" onClick={()=>onSelect("shared")} aria-label={`Filter Shared, ${money(values.shared)}, ${shared}%`} className="bg-indigo-600 text-xs font-semibold text-white focus-visible:ring-2 focus-visible:ring-indigo-500" style={{width:`${shared}%`}}>{shared>=15?`Shared ${shared}%`:null}</button></div><div className="flex justify-between gap-4 text-sm text-slate-700"><button type="button" onClick={()=>onSelect("personal")} className="rounded focus-visible:ring-2 focus-visible:ring-indigo-500">Personal {personal}% · {money(values.personal)}</button><button type="button" onClick={()=>onSelect("shared")} className="rounded focus-visible:ring-2 focus-visible:ring-indigo-500">Shared {shared}% · {money(values.shared)}</button></div></div>}
function CategoryTrend({values,granularity}:{values:{period:string;categories:Record<string,number>}[];granularity:"day"|"week"|"month"}){const aggregate=new Map<string,number>();values.forEach(value=>Object.entries(value.categories).forEach(([name,amount])=>aggregate.set(name,(aggregate.get(name)||0)+amount)));const grouped=groupSmallCategories([...aggregate].map(([name,amount_cents])=>({name,amount_cents})),6);const names=grouped.map(item=>item.name);const normalized=values.map(value=>{const categories:Record<string,number>={};let other=0;Object.entries(value.categories).forEach(([name,amount])=>{if(names.includes(name)&&name!=="Other")categories[name]=(categories[name]||0)+amount;else other+=amount});if(names.includes("Other")&&other)categories.Other=other;return {...value,categories}});const totals=normalized.map(v=>Object.values(v.categories).reduce((a,b)=>a+b,0));const max=Math.max(1,...totals);return <div className="overflow-x-auto"><div className="min-w-[560px]"><div className="flex h-64 items-end gap-1.5" role="img" aria-label="Stacked category composition over time">{normalized.map((value,i)=>{const tooltip=[dateLabel(value.period,granularity,true),...names.filter(name=>value.categories[name]).map(name=>`${name}: ${money(value.categories[name])}`),`Total: ${money(totals[i])}`].join("\n");return <button type="button" key={value.period} className="group flex h-full min-w-3 flex-1 flex-col justify-end rounded-sm focus-visible:ring-2 focus-visible:ring-indigo-500" title={tooltip} aria-label={tooltip}><span className="flex w-full flex-col-reverse overflow-hidden rounded-t" style={{height:`${totals[i]/max*100}%`}}>{names.map(name=><span key={name} style={{height:`${totals[i]?((value.categories[name]||0)/totals[i])*100:0}%`,backgroundColor:categoryColor(name)}}/>)}</span><span className="mt-1 truncate text-center text-xs text-slate-500">{dateLabel(value.period,granularity)}</span></button>})}</div><div className="mt-3 flex flex-wrap gap-3">{names.map(name=><span key={name} className="flex items-center gap-1 text-xs"><span className="h-2 w-2 rounded-sm" style={{backgroundColor:categoryColor(name)}}/>{name}</span>)}</div></div></div>}
function Changes({items}:{items:Insights["notable_changes"]}){return <div className="grid gap-2 sm:grid-cols-2">{items.length?items.map(item=>{const Icon=item.kind==="merchant"?Store:item.direction==="down"?ArrowDownRight:ArrowUpRight;return <div key={`${item.kind}-${item.label}`} className="flex items-start gap-3 rounded-lg bg-slate-50 px-3 py-3"><Icon className={`mt-0.5 h-4 w-4 ${item.direction==="down"?"text-sky-700":item.kind==="merchant"?"text-slate-600":"text-indigo-700"}`}/><div><p className="text-sm font-semibold text-slate-900">{item.label}</p><p className="text-xs text-slate-600">{item.detail}</p></div></div>}):<p className="text-sm text-slate-600">No major spending changes were detected for this period.</p>}</div>}
function Select({label,value,onChange,options,all}:{label:string;value:string;onChange:(v:string)=>void;options:string[];all:string}){return <label className="grid gap-1 text-xs font-semibold text-slate-700">{label}<select className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}><option value="">{all}</option>{options.map(v=><option key={v} value={v}>{title(v)}</option>)}</select></label>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-1 text-xs font-semibold text-slate-700">{label}<Input type="date" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Toggle({values,labels,value,onChange}:{values:string[];labels:string[];value:string;onChange:(v:string)=>void}){return <div className="flex rounded-lg bg-slate-100 p-1">{values.map((v,i)=><button key={v} type="button" onClick={()=>onChange(v)} aria-pressed={value===v} className={`rounded-md px-2 py-1 text-xs font-medium ${value===v?"bg-white text-indigo-700 shadow-sm":"text-slate-600"}`}>{labels[i]}</button>)}</div>}
function Chip({label,onRemove}:{label:string;onRemove:()=>void}){return <span className="inline-flex items-center gap-1 rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-800">{label}<button type="button" onClick={onRemove} aria-label={`Remove ${label}`}><X className="h-3 w-3"/></button></span>}
function CompactMessage({title,detail,action}:{title:string;detail:string;action?:()=>void}){return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center"><CircleDollarSign className="mx-auto h-6 w-6 text-slate-500"/><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-600">{detail}</p>{action?<Button className="mt-3" variant="outline" onClick={action}><RefreshCw className="h-4 w-4"/>Retry</Button>:null}</div>}
function DashboardSkeleton(){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" role="status" aria-label="Loading insights">{Array.from({length:5},(_,i)=><div key={i} className="ui-skeleton h-28 rounded-xl"/>)}</div>}
function title(value:string){return value.replace(/_/g," ").replace(/\b\w/g,v=>v.toUpperCase())}
function countComparison(current:number,previous:number){const delta=current-previous;if(!delta)return {primary:"No change",secondary:null};return {primary:`${delta>0?"+":"−"}${Math.abs(delta)} vs previous period`,secondary:null}}
